"""AELVO Provider/Runtime Ecosystem — full provider infrastructure.

This package provides a complete provider runtime ecosystem for AELVO,
supporting 20+ AI providers with unified auth, streaming normalization,
tool call normalization, health monitoring, fallback routing, diagnostics,
and extensible adapter patterns.
"""

from .types import (
    ProviderKind,
    ProviderStatus,
    ProviderInfo,
    ProviderConfig,
    ProviderError,
    ModelFamily,
    ModelConfig,
    Capability,
    AuthMethod,
    AuthConfig,
    Credential,
    CredentialType,
    HealthStatus,
    Usage,
    ChatMessage,
    CanonicalRequest,
    CanonicalResponse,
    StreamEvent,
    ToolCall,
    ToolDefinition,
    RoutingDecision,
    RoutingStrategy,
    FinishReason,
)
from .config import PROVIDER_REGISTRY, MODEL_REGISTRY
from .config import (
    get_provider,
    get_model,
    get_models_by_provider,
    get_models_by_family,
    get_providers_by_capability,
    get_models_by_capability,
    list_all_providers,
    list_all_models,
    get_local_providers,
    get_cloud_providers,
)
from .cred_storage import EncryptedCredentialStorage
from .auth.provider import ProviderAuthOrchestrator

__all__ = [
    "ProviderKind",
    "ProviderStatus",
    "ProviderInfo",
    "ProviderConfig",
    "ProviderError",
    "ModelFamily",
    "ModelConfig",
    "Capability",
    "AuthMethod",
    "AuthConfig",
    "Credential",
    "CredentialType",
    "HealthStatus",
    "Usage",
    "ChatMessage",
    "CanonicalRequest",
    "CanonicalResponse",
    "StreamEvent",
    "ToolCall",
    "ToolDefinition",
    "RoutingDecision",
    "RoutingStrategy",
    "FinishReason",
    "PROVIDER_REGISTRY",
    "MODEL_REGISTRY",
    "get_provider",
    "get_model",
    "get_models_by_provider",
    "get_models_by_family",
    "get_providers_by_capability",
    "get_models_by_capability",
    "list_all_providers",
    "list_all_models",
    "get_local_providers",
    "get_cloud_providers",
    "EncryptedCredentialStorage",
    "ProviderAuthOrchestrator",
]
