"""ARCHITECT MCP specialist integration contract."""

from __future__ import annotations

import logging
from typing import Any, Dict, List
from ...execution.execution_engine import MCPExecutionEngine
from ...execution.execution_request import MCPExecutionRequest
from ...execution.execution_result import MCPExecutionResult
from ...capability.capability_engine import CapabilityEngine
from ...registry.models import TrustLevel
from ...events.event_schemas import ExecutionPriority

log = logging.getLogger("aelvo.mcp.specialist.architect")


class MCPCapabilityAcquisitionStep:
    """A planning step to acquire a missing capability."""

    def __init__(self, required_capability: str, blocking: bool = True):
        self.required_capability = required_capability
        self.blocking = blocking
        self.strategy = "find_existing_server"


class ArchitectMCPInterface:
    """Specialist integration contract for ARCHITECT.

    Permitted MCP usage:
    - Query architecture reference servers
    - Retrieve planning resources and decision records
    - Query capability graphs for plan feasibility

    Key behavior:
    Plans generated by ARCHITECT may include MCPCapabilityAcquisitionStep nodes.
    """

    def __init__(self, execution_engine: MCPExecutionEngine, capability_engine: CapabilityEngine):
        self._execution_engine = execution_engine
        self._capability_engine = capability_engine

    async def check_plan_feasibility(self, plan_steps: List[str]) -> List[MCPCapabilityAcquisitionStep]:
        """Verify if all required capabilities for plan steps exist in the capability graph.

        Returns acquisition steps for missing capabilities.
        """
        acquisition_steps = []
        gaps = await self._capability_engine.get_capability_gaps()

        for step in plan_steps:
            for gap in gaps:
                # If a plan step depends on a capability gap, add acquisition step
                if gap.get("task_type") in step.lower() or gap.get("tool_name") in step.lower():
                    acquisition_steps.append(
                        MCPCapabilityAcquisitionStep(
                            required_capability=gap.get("task_type") or gap.get("tool_name", "unknown"),
                            blocking=True,
                        )
                    )

        return acquisition_steps

    async def execute_planning_query(
        self,
        server_id: str,
        tool_name: str,
        arguments: Dict[str, Any],
    ) -> MCPExecutionResult:
        """Query architecture servers for planning inputs."""
        request = MCPExecutionRequest(
            request_id=f"arch_req_{hash(tool_name) % 10000}",
            specialist_id="ARCHITECT",
            server_id=server_id,
            tool_name=tool_name,
            arguments=arguments,
            trust_requirement=TrustLevel.VERIFIED,
            priority=ExecutionPriority.NORMAL,
        )
        return await self._execution_engine.execute(request)
